language: r
sudo: true

r:
  - oldrel
  - release COVERAGE=true
  - devel

install_r:
  - covr

after_success:
  - if [[ ! -z "$COVERAGE" ]];then  Rscript -e 'covr::codecov()'; fi

notifications:
  email:
    on_success: change
    on_failure: change
    
