language: r
sudo: required

r:
  - release 
#  - oldrel
  #  - devel

r_binary_package: 
  - RcppZiggurat
  
install_r:
  - covr

before_install:
  - echo $TRAVIS_R_VERSION


after_success:
  - Rscript -e 'if(length(grep("1$", ${TRAVIS_JOB_NUMBER}$"))) covr::codecov()';

notifications:
  email:
    on_success: change
    on_failure: change
    
