language: r
cache: packages
r:
  - oldrel
  - release
  - devel

install_r:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
    
